### ISSUE TITLE
rework syntax

### ISSUE THREAD

**Issue by CG1122** [CG1122/DAL#6]
Current idea  would be to make it so that all items are variables and keyword pairs (not items) are attributes. This would make it much easy to make the syntax recursive and handle more complex data structures.

for example

```yaml

- numvar1:
    lower: 1
    upper:  2
- numvar2
- charvar1
- another_var:
    - subvar1
    - subvar2
```
